### ISSUE TITLE
KeyError: '281310'

### ISSUE THREAD

**Issue by jw44lavo** [c2-d2/rase-pipeline#16]
hi,
I have classified reads wiht prophyle successfully. Afterwards I wanted to use the RASE predict tool. 

command:
python3 rase_predict.py /sparc/spneumoniae-sparc.k18/tree.nw /sparc/spneumoniae-sparc.k18.tsv prophyle_read.bam > output.tsv1 

error:
Antibiotics in the RASE DB: cro, ery, pen, sxt, tet
datetime	reads	kbps	kkmers	ks	ls	ls_pass	ln	alt_ln	bm	bm_serotype	bm_ST	cro_ss	cro_pred	cro_bm	ery_ss	ery_pred	ery_bm	pen_ss	pen_pred	pen_bm	sxt_ss	sxt_pred	sxt_bm	tet_ss	tet_pred	tet_bm
2020-03-20 11:25:23	0	0	0	0.000	0	0	NA	NA	NA	NA	NA	0.000	R	NA (NA)	0.000	R	NA (NA)	0.000	R	NA (NA)	0.000	R	NA (NA)0.000	R	NA (NA)
Time t=0h1m: 0 reads and 0 kbps.
Traceback (most recent call last):
  File "scripts/rase/rase_predict.py", line 985, in <module>
    main()
  File "scripts/rase/rase_predict.py", line 979, in main
    r.run()
  File "scripts/rase/rase_predict.py", line 201, in run
    self.stats.update_from_read(read_stats)
  File "scripts/rase/rase_predict.py", line 519, in update_from_read
    bestmatching_isolates = self._descending_isolates(*nnames)
  File "scripts/rase/rase_predict.py", line 450, in _descending_isolates
    isolates |= self._descending_isolates_d[nname]
KeyError: '281310'

**Comment by karel-brinda** [comment]
Would it be possible to share a part of the bam file? For instance, `first_records.bam` obtained by
```
samtools view -h prophyle_read.bam | head -n 5000 | samtools view -b > first_records.bam
```

**Comment by karel-brinda** [comment]
Was the BAM file created with the same DB? The isolate `281310` doesn't exist in the S. pneumoniae SPARC DB.

**Comment by karel-brinda** [comment]
As no additional info was provided, I'm closing this for now (can be reopened in the future).
